CREATE TABLE QUESTIONINFOS
(
  ID            NUMBER,
  CONTENT       VARCHAR2(200 BYTE),
  IMAGEURL      VARCHAR2(200 BYTE),
  AUDIOURL      VARCHAR2(200 BYTE),
  VIDEOURL      VARCHAR2(200 BYTE),
  EXPLAINATION  VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
MONITORING;
