CREATE TABLE QUESTIONS
(
  ID                 NUMBER,
  USERID             VARCHAR2(200 BYTE),
  TYPEID             VARCHAR2(200 BYTE),
  SUBJECTID          VARCHAR2(200 BYTE),
  EDUCATIONLEVELID   VARCHAR2(200 BYTE),
  DIFFICULTLEVELTID  VARCHAR2(200 BYTE),
  LANGUAGEID         VARCHAR2(200 BYTE),
  POINTID            VARCHAR2(200 BYTE),
  PENALTYPOINTID     VARCHAR2(200 BYTE),
  QUESTIONINFOID     VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
MONITORING;
