CREATE TABLE SUBJECTS
(
  ID           NUMBER,
  NAME         VARCHAR2(200 BYTE),
  DESCRIPTION  VARCHAR2(4000 BYTE),
  PARENT_ID    NUMBER,
  VI           VARCHAR2(200 BYTE),
  EN           VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
MONITORING;
