CREATE TABLE TBL_FIELD_DECLARES
(
  ID    NUMBER,
  NAME  VARCHAR2(200 BYTE),
  VI    VARCHAR2(200 BYTE),
  EN    VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
MONITORING;
