CREATE TABLE TBL_ERRORS
(
  ID    NUMBER,
  CODE  VARCHAR2(200 BYTE),
  VI    VARCHAR2(4000 BYTE),
  EN    VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
MONITORING;
